Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,58 +1,106 @@
-# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
-# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
+# # This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
+# # For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
 
-name: Build, Deploy, and Upload Artifacts
+# name: Build, Deploy, and Upload Artifacts
+
+# on:
+#   push:
+#     branches:
+#       - '**'
+#   pull_request:
+#     branches:
+#       - master
+#   workflow_dispatch:
+
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
+#     steps:
+#       # Checkout the repository
+#       - name: Checkout Code
+#         uses: actions/checkout@v3
+
+#       # Set up Java
+#       - name: Set up Java 
+#         uses: actions/setup-java@v3
+#         with:
+#           java-version: '11'
+#           distribution: 'temurin'
+
+#       # Cache Maven dependencies
+#       - name: Cache Maven dependencies
+#         uses: actions/cache@v3
+#         with:
+#           path: ~/.m2
+#           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+#           restore-keys:
+
+#        # Install Maven (if not installed already)
+#       - name: Install Maven
+#         run: |
+#           if ! command -v mvn &> /dev/null; then
+#             echo "Maven not found, installing..."
+#             sudo apt update
+#             sudo apt install -y maven
+#           else
+#             echo "Maven is already installed"
+#           fi
+
+#       # Verify Maven installation
+#       - name: Verify Maven installation
+#         run: mvn -v
+
+
+#       - name: Configure Maven settings
+#         run: |
+#           mkdir -p ~/.m2
+#           echo "<settings>
+#                   <servers>
+#                     <server>
+#                       <id>hello-world-war</id>
+#                       <username>${{ secrets.ARTIFACTORY_USERNAME }}</username>
+#                       <password>${{ secrets.ARTIFACTORY_API_KEY }}</password>
+#                     </server>
+#                   </servers>
+#                 </settings>" > ~/.m2/settings.xml
+          
+#       # Build the project with Maven
+#       - name: Build with Maven
+#         run: mvn clean deploy
+
+
+# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
+# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
+
+# This workflow uses actions that are not certified by GitHub.
+# They are provided by a third-party and are governed by
+# separate terms of service, privacy policy, and support
+# documentation. 
+
+name: Java CI with Maven
 
 on:
   push:
-    branches:
-      - '**'
+    branches: [ "master" ]
   pull_request:
-    branches:
-      - master
-  workflow_dispatch:
+    branches: [ "master" ]
 
 jobs:
   build:
+
     runs-on: ubuntu-latest
+
     steps:
-      # Checkout the repository
-      - name: Checkout Code
-        uses: actions/checkout@v3
+    - uses: actions/checkout@v4
+    - name: Set up JDK 17
+      uses: actions/setup-java@v4
+      with:
+        java-version: '17'
+        distribution: 'temurin'
+        cache: maven
 
-      # Set up Java
-      - name: Set up Java 
-        uses: actions/setup-java@v3
-        with:
-          java-version: '11'
-          distribution: 'temurin'
-
-      # Cache Maven dependencies
-      - name: Cache Maven dependencies
-        uses: actions/cache@v3
-        with:
-          path: ~/.m2
-          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-          restore-keys:
-
-       # Install Maven (if not installed already)
-      - name: Install Maven
-        run: |
-          if ! command -v mvn &> /dev/null; then
-            echo "Maven not found, installing..."
-            sudo apt update
-            sudo apt install -y maven
-          else
-            echo "Maven is already installed"
-          fi
-
-      # Verify Maven installation
-      - name: Verify Maven installation
-        run: mvn -v
-
-
-      - name: Configure Maven settings
-        run: |
+    - name: Configure Maven settings
+      run: |
           mkdir -p ~/.m2
           echo "<settings>
                   <servers>
@@ -62,8 +110,7 @@ jobs:
                       <password>${{ secrets.ARTIFACTORY_API_KEY }}</password>
                     </server>
                   </servers>
-                </settings>" > ~/.m2/settings.xml
-          
-      # Build the project with Maven
-      - name: Build with Maven
-        run: mvn clean deploy
+                </settings>" > ~/.m2/settings.xml   
+        
+    - name: Build with Maven
+      run: mvn clean deploy
